language: java
sudo: false
install: true

jdk:
- oraclejdk8

addons:
  sonarcloud:
    organization: islomar-github
    token: $SONARCLOUD_TOKEN

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

after_success:
- mvn clean test jacoco:report coveralls:report
- mvn org.pitest:pitest-maven:mutationCoverage

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'